language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/python bootstrap.py --setuptools-version=34.3.0 --buildout-version=2.8.0  #from http://dist.plone.org/release/5.1-latest/versions.cfg 2017-05-30 11:22
install:
  - bin/buildout -Nvt 5 -c travis.cfg
script:
  - bin/test
